# Generated by Django 3.2.4 on 2021-07-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='modification',
            name='name',
            field=models.CharField(default='fff', max_length=200),
            preserve_default=False,
        ),
    ]
